---
# Create the keystone database

- name: Create keystone database
  mysql_db: login_user=root login_password='' name={{ item.name }} state=present
  with_items:
    - { name: 'keystone'}
  tags: keystone

- name: Grant proper access to the openstack database
  mysql_user: login_user=root login_password=''  name={{ item.name }} password={{ keystone_dbpass }} priv=*.*:ALL state=present
  with_items:
    - { name: 'keystone'}
  tags: keystone