---
#  Create openstack Keystone openstack service and endpoint api
- name: Create openstack service
  keystone_service: >
    name={{ item.name }}
    service_type={{ item.service_type }}
    description={{ item.description }}
    endpoint="http://{{ controller }}:35357/v2.0"
    token={{ keystone_admin_token }}
    state=present
  with_items:
    - { name: 'keystone',service_type: 'identity',description: "'OpenStack Identity'" }
  tags: keystone

- name: Create openstack endpoints
  keystone_endpoint: >
    service_name={{ item.service }}
    region={{ item.region }}
    public_url={{ item.public }}
    internal_url={{ item.internal }}
    admin_url={{ item.admin }}
    endpoint="http://{{ controller }}:35357/v2.0"
    token={{ admin_token }}
    state=present
  with_items:
    - { service: 'keystone',region: 'RegionOne',public: "'http://{{ controller }}:5000/v2.0'",internal: "'http://{{ controller }}:5000/v2.0'",admin: "'http://{{ controller }}:35357/v2.0'"}
  tags: keystone

#Create projects, users, and roles
- name: Create openstack tenants
  keystone_user: >
    tenant={{ item.tenant }}
    tenant_description={{ item.tenant_description }}
    endpoint="http://{{ controller }}:35357/v2.0"
    token="{{ admin_token }}"
    state=present
  with_items:
    - { tenant: 'admin',tenant_description: "'Admin Project'"}
    - { tenant: 'service',tenant_description: "'Service Project'"}
    - { tenant: 'demo',tenant_description: "'Demo Project'"}
  tags: keystone

- name: Create openstack users
  keystone_user: >
    user={{ item.user }}
    password={{ item.password }}
    tenant={{ item.tenant }}
    email={{ item.email }}
    endpoint="http://{{ controller }}:35357/v2.0"
    token={{ admin_token }}
    state=present
  with_items:
    - { user: 'admin', password: '{{ keystone_user_pass }} ',tenant: 'admin',email: 'admin@localhost'}
    - { user: 'demo', password: '{{ keystone_user_pass }}',tenant: 'demo',email: 'demo@localhost'}
  tags: keystone

- name: Add openstack roles to defined users in defined tenants
  keystone_user: >
   role={{ item.role }}
   user={{ item.user }}
   tenant={{ item.tenant }}
   endpoint="http://{{ controller }}:35357/v2.0"
   token="{{ admin_token }}"
   state=present
  with_items:
    - { role: 'admin',user: 'admin', tenant: 'admin'}
    - { role: 'user',user: 'demo', tenant: 'demo'}
  tags: keystone
