---
    - name : Install the agentd
      yum : name={{ item }}
      with_items:
            - zabbix-agent
    - name:  Configure zabbix
      lineinfile: dest=/etc/zabbix/zabbix_agentd.conf  regexp={{ item.s }} line={{ item.d }}
      with_items:
          - { s: "Server=",d: "Server={{ zabbix_server }}"}
          - { s: "ServerActive" ,d: "ServerActive={{ zabbix_server }}" }
          - { s: "^Hostname" ,d: "Hostname={{ ansible_nodename }}" }

    - name: zabbix_agent
      service: name=zabbix-agent.service state=started enabled=yes