---
# Create the openstack nova database

- name: Create  openstack database
  mysql_db: login_user=root login_password='' name={{ item.name }} state=present
  with_items:
    - { name: 'nova'}
  tags: nova_server_db

- name: Grant proper access to the openstack database
  mysql_user: login_user=root login_password='' name={{ item.name }} password={{ nova_dbpass }} host='%' priv=*.*:ALL state=present
  with_items:
    - { name: 'nova'}
  tags: nova_server_db