---
  - include: zabbix_server_package.yml
  - include: install.yml
  - include: init_database.yml
  - include: zabbix_server_config.yml
  - include: patch.yml
  - include: edit_firewall.yml
  - include: start.yml
