---
# Install and configure Glance

- name: Install the Glance package
  yum: name={{ item }}
  with_items:
      - openstack-glance
      - python-glance
      - python-glanceclient
  tags: glance

- name: Edit the /etc/glance/glance-api.conf file and complete the following actions
  ini_file: >
       dest=/etc/glance/glance-api.conf section={{ item.section }}  option={{ item.option }} value={{ item.value }} 
  with_items:
    - { section: 'database',option: 'connection ',value: 'mysql://glance:{{ glance_dbpass }}@{{ mysql_host }}/glance' }
    - { section: 'keystone_authtoken',option: 'auth_uri',value: 'http://{{ controller }}:5000'}
    - { section: 'keystone_authtoken',option: 'auth_url',value: 'http://{{ controller }}:35357'}
    - { section: 'keystone_authtoken',option: 'auth_plugin',value: 'password'}
    - { section: 'keystone_authtoken',option: 'project_domain_id',value: 'default'}
    - { section: 'keystone_authtoken',option: 'user_domain_id',value: 'default'}
    - { section: 'keystone_authtoken',option: 'project_name',value: 'service'}
    - { section: 'keystone_authtoken',option: 'username',value: 'glance'}
    - { section: 'keystone_authtoken',option: 'password',value: '{{ glance_pass}}'}
    - { section: 'paste_deploy',option: 'flavor',value: 'keystone'}  
    - { section: 'glance_store',option: 'default_store',value: 'file'}
    - { section: 'glance_store',option: 'filesystem_store_datadir',value: '/var/lib/glance/images/'}
    - { section: 'DEFAULT',option: 'notification_driver',value: 'noop'}
    - { section: 'DEFAULT',option: 'verbose',value: 'True'}
    - { section: 'DEFAULT',option: 'debug',value: 'True'}
  tags: glance


- name: Edit the /etc/glance/glance-registry.conf file and complete the following actions
  ini_file: >
       dest=/etc/glance/glance-registry.conf section={{ item.section }}  option={{ item.option }} value={{ item.value }} 
  with_items:
    - { section: 'database',option: 'connection ',value: 'mysql://glance:{{ glance_dbpass }}@{{ mysql_host }}/glance' }
    - { section: 'keystone_authtoken',option: 'auth_uri',value: 'http://{{ controller }}:5000'}
    - { section: 'keystone_authtoken',option: 'auth_url',value: 'http://{{ controller }}:35357'}
    - { section: 'keystone_authtoken',option: 'auth_plugin',value: 'password'}
    - { section: 'keystone_authtoken',option: 'project_domain_id',value: 'default'}
    - { section: 'keystone_authtoken',option: 'user_domain_id',value: 'default'}
    - { section: 'keystone_authtoken',option: 'project_name',value: 'service'}
    - { section: 'keystone_authtoken',option: 'username',value: 'glance'}
    - { section: 'keystone_authtoken',option: 'password',value: '{{ glance_pass}}'}
    - { section: 'paste_deploy',option: 'flavor',value: 'keystone'}
    - { section: 'DEFAULT',option: 'notification_driver',value: 'noop'}
    - { section: 'DEFAULT',option: 'verbose',value: 'True'}
    - { section: 'DEFAULT',option: 'debug',value: 'True'}
  tags: glance

- name: glance_manage_db_sync
  shell: su -s /bin/sh -c "glance-manage db_sync" glance
  tags: glance

- name: restart_openstack_glance_service_and_Boot_enable
  service: name={{ item }}  state=restarted  enabled=yes
  with_items:
        - openstack-glance-api.service
        - openstack-glance-registry.service
  tags: glance