---
  - name: zabbix_proxy_package
    yum: name={{ item }} state=present
    with_items: 
      - net-snmp 
      - net-snmp-devel 
      - perl-DBI  
      - ntpdate   
      - libxml2-devel 
      - fping 
      - ipmitool
      - telnet
      - wget
      - OpenIPMI
      - ipmitool
      - MySQL-python
    tags: zabbix_proxy_package