---
# Create the openstack database
- name: Create  openstack database
  mysql_db: login_user=root login_password=''  name={{ item.name }} state=present
  with_items:
    - { name: 'neutron' }
  tags: neutron_server_db

- name: Grant proper access to the openstack database
  mysql_user: login_user=root login_password=''  name={{ item.name }} password={{ neutron_dbpass  }} host='%' priv=*.*:ALL state=present
  with_items:
    - { name: 'neutron'}
  tags: neutron_server_db