---
  - name: zabbix_proxy_config
    copy: src={{ item.a }} dest={{ item.b }} group={{ item.c }} owner={{ item.d }} mode={{ item.e }} force=yes
    with_items:
      - { a: 'zabbix_proxy.conf',b: '/etc/zabbix/',c: 'root',d: 'zabbix',e: '0640' }
      - { a: 'zabbix_agentd.conf',b: '/etc/zabbix/',c: 'root',d: 'root',e: '0644' }
    tags: zabbix_proxy_config

  - name: edit_zabbix_proxy_config
    lineinfile: dest=/etc/zabbix/zabbix_proxy.conf regexp={{ item.s }} line={{ item.d }}
    with_items:
      - { s: "^DBPassword=",d: "DBPassword={{ mysqldb_password }}" }
      - { s: "^Server=",d: "Server={{ zabbix_server_ip }}" }
      - { s: "^Hostname=",d: "Hostname={{ ansible_hostname }}" }
    tags: edit_zabbix_proxy_config

  - name: edit_mysql_config
    ini_file: dest=/etc/my.cnf section={{ item.section }} option={{ item.option }} value={{ item.value }}
    with_items:
      - { section: 'mysqld',option: 'max_connections',value: '1000' }
    tags: edit_mysql_config

  - name: edit_zabbix_agent_config
    lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp={{ item.s }} line={{ item.d }}
    with_items:
      - { s: "^Server=",d: "Server=127.0.0.1" }
      - { s: "^ServerActive=",d: "ServerActive=127.0.0.1" }
      - { s: "^Hostname=",d: "Hostname={{ ansible_hostname }}" }
    tags: edit_zabbix_agent_config