---
  - name: install zabbix_server repo
    yum: name={{ item }} state=present
    with_items:
      - zabbix-server-mysql
      - zabbix-web-mysql
      - zabbix-agent
    tags: install zabbix_server repo