---
  - name: start_service
    service: name={{ item }} state=started enabled=yes
    with_items:
      - httpd
      - mysqld
      - zabbix-server
      - zabbix-agent
      - firewalld
    tags: start_service