---
    - name: Install the Rabbitmq package
      yum: name=rabbitmq-server
    - name: add host
      shell: echo "127.0.0.1  {{ ansible_nodename }}" >>/etc/hosts
    - name: restart Rabbitmq-server and Boot enable
      service: name=rabbitmq-server.service  state=started enabled=yes

    - name: Config the Rabbitmq add user
      rabbitmq_user: user={{ rabbit_user }} password={{ rabbit_pass }} vhost=/ configure_priv=.* read_priv=.* write_priv=.* state=present

    - name: Enables the rabbitmq_management plugin
      rabbitmq_plugin: names=rabbitmq_management state=enabled
