---

- include: neutron-db.yml
- include: neutron-install.yml
- include: ml2.yml
- include: bridge-agent.yml
- include: l3-agent.yml
- include: dhcp-agent.yml
- include: metadata-agent.yml
- include: neutron-nova.yml
- include: service-enable.yml