---
# Install and configure neutron
- name: Install the Nova package
  yum: name={{ item }}
  with_items:
    - openstack-neutron
    - openstack-neutron-ml2
    - openstack-neutron-linuxbridge
    - python-neutronclient
    - ebtables
    - ipset
  tags: neutron

- name: Edit the /etc/neutron/neutron.conf  file and complete the following actions
  ini_file: >
       dest=/etc/neutron/neutron.conf  section={{ item.section }}  option={{ item.option }} value={{ item.value }} 
  with_items:
    - { section: 'database',option: 'connection ',value: 'mysql://neutron:{{ neutron_dbpass }}@{{ mysql_host }}/neutron' }
    - { section: 'DEFAULT',option: 'core_plugin ',value: 'ml2'}
    - { section: 'DEFAULT',option: 'service_plugins ',value: 'router'}
    - { section: 'DEFAULT',option: 'allow_overlapping_ips ',value: 'True'}
    - { section: 'DEFAULT',option: 'rpc_backend ',value: 'rabbit'}
    - { section: 'oslo_messaging_rabbit',option: 'rabbit_host',value: '{{ controller }}'}
    - { section: 'oslo_messaging_rabbit',option: 'rabbit_userid',value: '{{ rabbit_user }}'}
    - { section: 'oslo_messaging_rabbit',option: 'rabbit_password',value: '{{ rabbit_pass }}'}
    - { section: 'DEFAULT',option: 'auth_strategy ',value: 'keystone'}
    - { section: 'DEFAULT',option: 'notify_nova_on_port_status_changes ',value: 'True'}
    - { section: 'DEFAULT',option: 'notify_nova_on_port_data_changes ',value: 'True'}
    - { section: 'DEFAULT',option: 'nova_url ',value: 'http://{{ controller }}:8774/v2'}
    - { section: 'keystone_authtoken',option: 'auth_uri',value: 'http://{{ controller }}:5000'}
    - { section: 'keystone_authtoken',option: 'auth_url',value: 'http://{{ controller }}:35357'}
    - { section: 'keystone_authtoken',option: 'auth_plugin',value: 'password'}
    - { section: 'keystone_authtoken',option: 'project_domain_id',value: 'default'}
    - { section: 'keystone_authtoken',option: 'user_domain_id',value: 'default'}
    - { section: 'keystone_authtoken',option: 'project_name',value: 'service'}
    - { section: 'keystone_authtoken',option: 'username',value: 'neutron'}
    - { section: 'keystone_authtoken',option: 'password',value: '{{ neutron_pass }}'}
    - { section: 'nova',option: 'auth_url ',value: 'http://{{ controller }}:35357'}
    - { section: 'nova',option: 'auth_plugin ',value: 'password'}
    - { section: 'nova',option: 'project_domain_id',value: 'default'}
    - { section: 'nova',option: 'user_domain_id ',value: 'default'}
    - { section: 'nova',option: 'region_name ',value: 'RegionOne'}
    - { section: 'nova',option: 'project_name ',value: 'service'}
    - { section: 'nova',option: 'username ',value: 'nova'}
    - { section: 'nova',option: 'password ',value: '{{ nova_pass }}'}
    - { section: 'oslo_concurrency',option: 'lock_path ',value: '/var/lib/neutron/tmp'}
    - { section: 'DEFAULT',option: 'verbose ',value: 'True'}
    - { section: 'DEFAULT',option: 'debug',value: 'True'}
  tags: neutron