---
- name: symbolic link /etc/neutron/plugin.ini pointing to the ML2 plug-in
  shell: ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini
  tags: neutron
  
- name: neutron_manage_db_sync
  shell: su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
  tags: neutron

- name: restart_openstack_nova_service_and_Boot_enable
  service: name={{ item }}  state=restarted enabled=yes
  with_items:
    - openstack-nova-api.service
    - neutron-server.service
    - neutron-linuxbridge-agent.service
    - neutron-dhcp-agent.service
    - neutron-metadata-agent.service
    - neutron-l3-agent.service
  tags: neutron